# serverless.yml

service: avkonnect-notifications

provider:
    name: aws
    runtime: nodejs14.x
    region: ap-south-1
    lambdaHashingVersion: 20201221
    apiGateway:
        binaryMediaTypes:
            - '*/*'
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
          Resource: '*'

package:
    patterns:
        - '!*'
        - '!src/**'
        - 'node_modules'
        - 'build'
        - '.env'

resources:
    Resources:
        NotificationsSQSQueue:
            Type: 'AWS::SQS::Queue'
            Properties:
                QueueName: avkonnect-notifications-queue-${opt:stage, self:provider.stage}

functions:
    notifications:
        handler: ./build/serverless.handler
        events:
            - http:
                  path: api/v1
                  method: any
                  request:
                      contentHandling: CONVERT_TO_TEXT
            - http: 'ANY {proxy+}'
    notifications-generator:
        handler: ./build/events/index.handler
        events:
            - sqs:
                  arn:
                      Fn::GetAtt:
                          - NotificationsSQSQueue
                          - Arn
                  batchSize: 10
                  maximumBatchingWindow: 60
